// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListAvailableMonths() {
  return window['go']['main']['App']['ListAvailableMonths']();
}

export function ListFichas(arg1, arg2) {
  return window['go']['main']['App']['ListFichas'](arg1, arg2);
}

export function RegisterFicha(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterFicha'](arg1, arg2, arg3);
}
