// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2);
}

export function DeleteACS(arg1) {
  return window['go']['main']['App']['DeleteACS'](arg1);
}

export function DeleteFicha(arg1) {
  return window['go']['main']['App']['DeleteFicha'](arg1);
}

export function HasAccount() {
  return window['go']['main']['App']['HasAccount']();
}

export function ListACS() {
  return window['go']['main']['App']['ListACS']();
}

export function ListAvailableMonths() {
  return window['go']['main']['App']['ListAvailableMonths']();
}

export function ListFichas(arg1, arg2) {
  return window['go']['main']['App']['ListFichas'](arg1, arg2);
}

export function ListFichasByACS(arg1) {
  return window['go']['main']['App']['ListFichasByACS'](arg1);
}

export function ListRequestTypes() {
  return window['go']['main']['App']['ListRequestTypes']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function RegisterACS(arg1, arg2) {
  return window['go']['main']['App']['RegisterACS'](arg1, arg2);
}

export function RegisterFicha(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RegisterFicha'](arg1, arg2, arg3, arg4, arg5);
}

export function StatsByACS(arg1, arg2) {
  return window['go']['main']['App']['StatsByACS'](arg1, arg2);
}

export function StatsByRequestType(arg1, arg2) {
  return window['go']['main']['App']['StatsByRequestType'](arg1, arg2);
}

export function UpdateACS(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateACS'](arg1, arg2, arg3);
}

export function UpdateFicha(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateFicha'](arg1, arg2, arg3, arg4, arg5, arg6);
}
