// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAccount(arg1:string,arg2:string):Promise<void>;

export function DeleteACS(arg1:string):Promise<void>;

export function DeleteFicha(arg1:string):Promise<void>;

export function HasAccount():Promise<boolean>;

export function ListACS():Promise<Array<main.ACSView>>;

export function ListAvailableMonths():Promise<Array<string>>;

export function ListFichas(arg1:string,arg2:string):Promise<Array<main.FichaView>>;

export function ListFichasByACS(arg1:string):Promise<Array<main.FichaView>>;

export function ListRequestTypes():Promise<Array<string>>;

export function Login(arg1:string,arg2:string):Promise<void>;

export function RegisterACS(arg1:string,arg2:string):Promise<main.ACSView>;

export function RegisterFicha(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<main.FichaView>;

export function UpdateACS(arg1:string,arg2:string,arg3:string):Promise<main.ACSView>;

export function UpdateFicha(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<main.FichaView>;
