// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ListFichas() {
  return window['go']['main']['App']['ListFichas']();
}

export function RegisterFicha(arg1, arg2, arg3) {
  return window['go']['main']['App']['RegisterFicha'](arg1, arg2, arg3);
}

export function SearchFichasByName(arg1) {
  return window['go']['main']['App']['SearchFichasByName'](arg1);
}
