// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListFichas():Promise<Array<main.FichaView>>;

export function RegisterFicha(arg1:string,arg2:string,arg3:string):Promise<main.FichaView>;

export function SearchFichasByName(arg1:string):Promise<Array<main.FichaView>>;
