// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ListAvailableMonths():Promise<Array<string>>;

export function ListFichas(arg1:string,arg2:string):Promise<Array<main.FichaView>>;

export function RegisterFicha(arg1:string,arg2:string,arg3:string):Promise<main.FichaView>;
